spring:
  application:
    name: market
  datasource:
    url: jdbc:postgresql://localhost:5432/market
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true